### ISSUE TITLE
actual gem broken (gentoo and sabayon)

### ISSUE THREAD

**Issue by ant11** [jeffWelling/ticgit#81]
Hi,
I did several fresh installtions of ticgit gem like it is described, but when I call ti the first time, I get this:

 ti
/usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:190:in `ioctl': Inappropriate ioctl for device - <STDOUT> (Errno::ENOTTY)
    from /usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:190:in`try_using'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:179:in `reset_window_width'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:274:in`<top (required)>'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng.rb:38:in `<top (required)>'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/TicGit-ng-1.0.2.17/bin/ti:11:in`<top (required)>'
    from /usr/local/bin/ti:23:in `load'
    from /usr/local/bin/ti:23:in`<main>'

Can this be fixed as I really like the idea of ticgit. Also an other question would be, once ticgit is working again, can it be compiled to a bin package (I am a newbie regarding ruby)?

**Comment by loucal** [comment]
Hi @ant11, until this pull request gets merged in you can use my fork like so 

```
gem install git
git clone https://github.com/loucal/ticgit.git
cd ticgit/
gem build ticgit-ng.gemspec
cd .. #the .rvmrc file in ticgit/ will cause it to be installed under a gemset
gem install ticgit/TicGit-ng-1.0.2.17.gem
```
